### ISSUE TITLE
some modification suggest for submitDocument Function 

### ISSUE THREAD

**Issue by voonvoon** [syukranDev/e-invoice-sdk-nodejs#1]
some modification suggest for submitDocument Function :

i commented this out:
    // const payload = {
    //   documents: docs,
    // };

Do this:
const payload = docs;  

Otherwise get error:

documentSubmissionResponse----> {
  status: 'failed',
  error: {
    error: {
      code: 'ValidationError',
      message: 'Invalid structure',
      target: 'submission',
      details: null
    }
  }
}

Thanks

**Comment by syukranDev** [comment]
Client side need to handle how's the `docs` will looks like:

Example:

```
let docs = [];

 docs.push({
        format: 'JSON',
        documentHash <== assign value accordingly
        codeNumber <== assign value accordingly
        document <== assign value accordingly
 })
```

```
 const einvois = require('./einvoice-sdk.js');
 let responseData = await einvois.submitDocument(docs, token)
```
